include:
  - aggregator/docker-compose.dev.yml
  - newsdata-parser/docker-compose.dev.yml
  - iz-parser/docker-compose.dev.yml

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=devuser
      - RABBITMQ_DEFAULT_PASS=test123