services:
  ria-cache:
    restart: unless-stopped
    image: redis:7.2-alpine3.19
    ports:
      - 4004:6379
    environment:
      REDIS_PASSWORD: test123
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 5

  ria-parser:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./ria-parser/app.Dockerfile
    command: [ "-c", "configs/docker.dev.yml" ]
    depends_on:
      ria-cache:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs
