services:
  newsdata-cache:
    restart: unless-stopped
    image: redis:7.2-alpine3.19
    ports:
      - 4001:6379
    environment:
      REDIS_PASSWORD: test123
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 5

  newsdata-parser:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./newsdata-parser/app.Dockerfile
    command: [ "-c", "configs/local.docker.dev.yml" ]
    depends_on:
      newsdata-cache:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs
